spring:
  application:
    name: ${APP_NAME:pr-lab1-producer}

server:
  address: ${ADDRESS:0.0.0.0}
  port: ${PORT:8070}

consumer:
  address: ${CONSUMER_ADDRESS:localhost}
  port: ${CONSUMER_PORT:3777}

dinning:
  tables: ${TABLE_COUNT:3}