spring:
  application:
    name: ${APP_NAME:pr-lab1-producer-dev}

server:
  address: ${ADDRESS:0.0.0.0}
  port: ${PORT:8077}

consumer:
  address: ${CONSUMER_ADDRESS:localhost}
  port: ${CONSUMER_PORT:8088}

dinning:
  tables: ${TABLE_COUNT:10}